In [4]:
import numpy as np
#From Python List
arr=np.array([1,2,3])
arr_2d_=np.array([[1,2,3],[4,5,6]])
print("the array is ",arr)
print("the 2d array is",arr_2d_)


the array is  [1 2 3]
the 2d array is [[1 2 3]
 [4 5 6]]


In [9]:
# Special Arrays
print(np.zeros((3, 3)))
print(np.ones((2, 4)))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.rand(3, 2))
print(np.random.randn(3, 2))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.37074718 0.22337606]
 [0.93818642 0.86725185]
 [0.1263286  0.03935589]]
[[0.49426106 0.6084156 ]
 [1.57871981 1.74748489]
 [0.85471105 0.43576513]]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [12]:
# Basic Math
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(np.sin(a))

[5 7 9]
[ 4 10 18]
[0.84147098 0.90929743 0.14112001]


In [10]:
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))
print(A @ B)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [11]:
# Aggregation
arr = np.array([1, 2, 3, 4])
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.std())


10
2.5
4
1
1.118033988749895


In [14]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[1:4])
print(arr[::2])

1
[2 3 4]
[1 3 5]


In [15]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])
print(arr[:, 1])
print(arr[1, :2])

2
[2 5]
[4 5]


In [17]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr>3
print(arr[mask])

[4 5]


In [2]:
# Reshape
import numpy as np
arr = np.arange(6)
print(arr.reshape(2, 3))

[[0 1 2]
 [3 4 5]]


In [3]:
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))

[1 2 3 4]


In [4]:
# Stacking
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [11]:
a = np.array([1, 2, 3])
a + 5

array([6, 7, 8])

In [7]:
#save to a file 
np.save('array.npy', arr)

In [8]:
# Load from a file
loaded_arr = np.load('array.npy')